


```{r}
uber_data_april = read.csv("DataSets_uber-pickups-in-new-york-city/uber-raw-data-apr14.csv")
uber_data_april
summary(uber_data_april)
str(uber_data_april)

uber_data_aug = read.csv("DataSets_uber-pickups-in-new-york-city/uber-raw-data-aug14.csv")
uber_data_aug
summary(uber_data_aug)
str(uber_data_aug)

uber_data_july = read.csv("DataSets_uber-pickups-in-new-york-city/uber-raw-data-jul14.csv")
uber_data_july
summary(uber_data_july)
str(uber_data_july)

uber_data_june = read.csv("DataSets_uber-pickups-in-new-york-city/uber-raw-data-jun14.csv")
uber_data_june
summary(uber_data_june)
str(uber_data_june)

uber_data_may = read.csv("DataSets_uber-pickups-in-new-york-city/uber-raw-data-may14.csv")
uber_data_may
summary(uber_data_may)
str(uber_data_may)

uber_data_sep = read.csv("DataSets_uber-pickups-in-new-york-city/uber-raw-data-sep14.csv")
uber_data_sep
summary(uber_data_sep)
str(uber_data_sep)


uber_data_janjune = read.csv("DataSets_uber-pickups-in-new-york-city/uber-raw-data-janjune-15.csv")
uber_data_janjune
summary(uber_data_janjune)
str(uber_data_janjune)

#Merge Datasets
uber_data_14 <- rbind(uber_data_april, uber_data_july, uber_data_june, uber_data_may, uber_data_sep, uber_data_janjune, uber_data_aug)

summary(uber_data_14)
str(uber_data_14)
```


```{r}
#CLEANING DATA: CHECK FOR UNIQUENESS AND NAN-VALUES

#----------------------------------------------------------------------------------
#NAN-values

# Check for missing values in each column
missing_values <- colSums(is.na(uber_data_14))

# Display the count of missing values in each column
print("Missing values in each column:")
print(missing_values)

#Since there is no missing value we do not change anything

#-----------------------------------------------------------------------------------
#UNIQUENESS
# Identify duplicate rows
duplicated_rows <- duplicated(uber_data_14)

# Count the number of duplicate rows
num_duplicates <- sum(duplicated_rows)


# Check if there are any duplicate rows
if (num_duplicates > 0) {
  # Display duplicate rows
  print("Number of duplicate rows:")
  print(num_duplicates)
  

} else {
  print("No duplicate rows.")
}

# Remove duplicated rows
uber_data_14_cleaned <- unique(uber_data_14)

# Identify duplicate rows
duplicated_rows <- duplicated(uber_data_14_cleaned)

# Count the number of duplicate rows
num_duplicates <- sum(duplicated_rows)

# Check if the new df contains  any duplicate rows
if (num_duplicates > 0) {
  # Display duplicate rows
  print("Number of duplicate rows:")
  print(num_duplicates)

} else {
  print("No duplicate rows.")
}

```


```{r}
#Average Passenger Determination:

# Ensure that the 'date' column is of type Date
uber_data_14_cleaned$Date.Time <- as.Date(uber_data_14_cleaned$Date.Time)

# Calculate the daily count of Uber trips using the table function
# table: Count the occurrences of each unique date in the 'date' column
daily_trip_counts <- table(uber_data_14_cleaned$Date.Time)

# Create a new dataframe with the results
# names(daily_trip_counts): Extract the unique dates from the result of table
# as.numeric(): Convert the count values to numeric
# date: The unique dates
# trip_counts: The count of Uber trips for each date
result_data <- data.frame(date = as.Date(names(daily_trip_counts)), trip_counts = as.numeric(daily_trip_counts))

# Display the results
print(result_data)
summary(result_data)
str(result_data)
```